apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: "demo-policy.example.com"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: "object.spec.replicas <= 5"
      messageExpression: "object.spec.replicas must be less than or equal to 5"
  auditAnnotations: 
    - key: "first audit annotation"
      valueExpression: type(object.spec.metadata.name('[0-9]+'))
  matchConditions:
    - name: "first name condition"
      expression: "object.spec.replicas <= 5"
    